<?php

// to do: add 2.4 achievements
global $achievements;
$achievements=array();
define('achievements_loaded', true);
$achievements[1]=array("title"=>"To Crush Your Enemies I", "points"=>"5");
$achievements[2]=array("title"=>"To Crush Your Enemies II", "points"=>"5");
$achievements[3]=array("title"=>"To Crush Your Enemies III", "points"=>"10");
$achievements[4]=array("title"=>"To Crush Your Enemies IV", "points"=>"10");
$achievements[5]=array("title"=>"To Crush Your Enemies V", "points"=>"10");
$achievements[6]=array("title"=>"To Crush Your Enemies VI", "points"=>"10");
$achievements[7]=array("title"=>"Let the Bodies Hit the Floor", "points"=>"30");
$achievements[728]=array("title"=>"Bump on a Log: Gladiator", "points"=>"20");
$achievements[729]=array("title"=>"Bump on a Log: Pugilist", "points"=>"20");
$achievements[730]=array("title"=>"Bump on a Log: Marauder", "points"=>"20");
$achievements[731]=array("title"=>"Bump on a Log: Lancer", "points"=>"20");
$achievements[732]=array("title"=>"Bump on a Log: Archer", "points"=>"20");
$achievements[733]=array("title"=>"Bump on a Log: Conjurer", "points"=>"20");
$achievements[734]=array("title"=>"Bump on a Log: Thaumaturge", "points"=>"20");
$achievements[735]=array("title"=>"Bump on a Log: Arcanist", "points"=>"20");
$achievements[792]=array("title"=>"Locking Horns", "points"=>"10");
$achievements[793]=array("title"=>"Uncut", "points"=>"10");
$achievements[794]=array("title"=>"When the Going Gets Tough", "points"=>"10");
$achievements[795]=array("title"=>"On the Ropes", "points"=>"10");
$achievements[796]=array("title"=>"Full Remission", "points"=>"10");
$achievements[797]=array("title"=>"Lazy Town", "points"=>"10");
$achievements[798]=array("title"=>"Blood, Sweat, and Blood", "points"=>"10");
$achievements[799]=array("title"=>"Ring of Fire", "points"=>"10");
$achievements[800]=array("title"=>"Boughbury Burning", "points"=>"10");
$achievements[801]=array("title"=>"Curtain Call", "points"=>"10");
$achievements[802]=array("title"=>"Old Maid", "points"=>"10");
$achievements[803]=array("title"=>"Date With Destiny I", "points"=>"5");
$achievements[804]=array("title"=>"Date With Destiny II", "points"=>"5");
$achievements[805]=array("title"=>"Date With Destiny III", "points"=>"10");
$achievements[806]=array("title"=>"Date With Destiny IV", "points"=>"10");
$achievements[807]=array("title"=>"Destiny's Child", "points"=>"20");
$achievements[808]=array("title"=>"Bosom Buddies I", "points"=>"5");
$achievements[809]=array("title"=>"Bosom Buddies II", "points"=>"10");
$achievements[810]=array("title"=>"Bosom Buddies III", "points"=>"20");
$achievements[885]=array("title"=>"The Kindness of Strangers", "points"=>"5");
$achievements[886]=array("title"=>"The Kindness of Strangers II", "points"=>"10");
$achievements[919]=array("title"=>"A Tankless Job I (Paladin)", "points"=>"5");
$achievements[920]=array("title"=>"A Tankless Job II (Paladin)", "points"=>"10");
$achievements[921]=array("title"=>"But Somebody's Gotta Do It (Paladin)", "points"=>"20");
$achievements[922]=array("title"=>"A Tankless Job I (Warrior)", "points"=>"5");
$achievements[923]=array("title"=>"A Tankless Job II (Warrior)", "points"=>"10");
$achievements[924]=array("title"=>"But Somebody's Gotta Do It (Warrior)", "points"=>"20");
$achievements[739]=array("title"=>"To the Dungeons I", "points"=>"5");
$achievements[740]=array("title"=>"To the Dungeons II", "points"=>"10");
$achievements[741]=array("title"=>"To the Dungeons III", "points"=>"20");
$achievements[742]=array("title"=>"Dungeon Siege I", "points"=>"5");
$achievements[743]=array("title"=>"Dungeon Siege II", "points"=>"5");
$achievements[744]=array("title"=>"Dungeon Siege III", "points"=>"5");
$achievements[745]=array("title"=>"Dungeon Siege IV", "points"=>"10");
$achievements[746]=array("title"=>"Dungeon Master", "points"=>"20");
$achievements[855]=array("title"=>"Going Up in Flames", "points"=>"10");
$achievements[856]=array("title"=>"Gone with the Wind", "points"=>"10");
$achievements[857]=array("title"=>"Earth to Earth", "points"=>"10");
$achievements[893]=array("title"=>"I Eat Whorls for Breakfast", "points"=>"10");
$achievements[894]=array("title"=>"Good Kingslayer", "points"=>"10");
$achievements[994]=array("title"=>"Contempt of Court", "points"=>"10");
$achievements[747]=array("title"=>"The Binds that Tie I", "points"=>"5");
$achievements[748]=array("title"=>"The Binds that Tie II", "points"=>"10");
$achievements[749]=array("title"=>"The Binds that Tie III", "points"=>"20");
$achievements[883]=array("title"=>"You Call That a Labyrinth", "points"=>"10");
$achievements[887]=array("title"=>"In Another Bind I", "points"=>"5");
$achievements[888]=array("title"=>"In Another Bind II", "points"=>"10");
$achievements[889]=array("title"=>"In Another Bind III", "points"=>"20");
$achievements[995]=array("title"=>"Life is a Syrcus", "points"=>"10");
$achievements[997]=array("title"=>"A Flower by Any Other Name", "points"=>"10");
$achievements[998]=array("title"=>"Seconds", "points"=>"10");
$achievements[999]=array("title"=>"Obtanium", "points"=>"10");
$achievements[1000]=array("title"=>"Scent of a Woman", "points"=>"10");
$achievements[843]=array("title"=>"Hungry Like a Wolf I", "points"=>"5");
$achievements[844]=array("title"=>"Hungry Like a Wolf II", "points"=>"5");
$achievements[845]=array("title"=>"Hungry Like a Wolf III", "points"=>"5");
$achievements[846]=array("title"=>"Hungry Like a Wolf IV", "points"=>"5");
$achievements[847]=array("title"=>"Hungry Like a Wolf V", "points"=>"10");
$achievements[848]=array("title"=>"Wolfing It Down", "points"=>"20");
$achievements[849]=array("title"=>"Pack Mentality I", "points"=>"5");
$achievements[850]=array("title"=>"Pack Mentality II", "points"=>"5");
$achievements[851]=array("title"=>"Pack Mentality III", "points"=>"5");
$achievements[852]=array("title"=>"Pack Mentality IV", "points"=>"5");
$achievements[853]=array("title"=>"Pack Mentality V", "points"=>"10");
$achievements[854]=array("title"=>"Leader of the Pack", "points"=>"20");
$achievements[930]=array("title"=>"Walk the Line I", "points"=>"5");
$achievements[931]=array("title"=>"Walk the Line II", "points"=>"5");
$achievements[932]=array("title"=>"Walk the Line III", "points"=>"5");
$achievements[933]=array("title"=>"Walk the Line IV", "points"=>"5");
$achievements[934]=array("title"=>"Walk the Line V", "points"=>"10");
$achievements[935]=array("title"=>"Life on the Line", "points"=>"20");
$achievements[936]=array("title"=>"A Line in the Storm I", "points"=>"5");
$achievements[937]=array("title"=>"A Line in the Storm II", "points"=>"5");
$achievements[938]=array("title"=>"A Line in the Storm III", "points"=>"5");
$achievements[939]=array("title"=>"A Line in the Storm IV", "points"=>"5");
$achievements[940]=array("title"=>"A Line in the Storm V", "points"=>"10");
$achievements[941]=array("title"=>"The Amethyst Keel", "points"=>"20");
$achievements[942]=array("title"=>"A Line in the Glade I", "points"=>"5");
$achievements[943]=array("title"=>"A Line in the Glade II", "points"=>"5");
$achievements[944]=array("title"=>"A Line in the Glade III", "points"=>"5");
$achievements[945]=array("title"=>"A Line in the Glade IV", "points"=>"5");
$achievements[946]=array("title"=>"A Line in the Glade V", "points"=>"10");
$achievements[947]=array("title"=>"The Ebony Leaf", "points"=>"20");
$achievements[948]=array("title"=>"A Line in the Sand I", "points"=>"5");
$achievements[949]=array("title"=>"A Line in the Sand II", "points"=>"5");
$achievements[950]=array("title"=>"A Line in the Sand III", "points"=>"5");
$achievements[951]=array("title"=>"A Line in the Sand IV", "points"=>"5");
$achievements[952]=array("title"=>"A Line in the Sand V", "points"=>"10");
$achievements[953]=array("title"=>"The Rose Gold Scales", "points"=>"20");
$achievements[954]=array("title"=>"Prime Air I", "points"=>"5");
$achievements[955]=array("title"=>"Prime Air II", "points"=>"5");
$achievements[956]=array("title"=>"Prime Air III", "points"=>"5");
$achievements[957]=array("title"=>"Prime Air IV", "points"=>"5");
$achievements[958]=array("title"=>"A Drone in the Dark", "points"=>"10");
$achievements[959]=array("title"=>"Just Say Node I", "points"=>"5");
$achievements[960]=array("title"=>"Just Say Node II", "points"=>"5");
$achievements[961]=array("title"=>"Just Say Node III", "points"=>"5");
$achievements[962]=array("title"=>"Just Say Node IV", "points"=>"5");
$achievements[963]=array("title"=>"A Node off My Back", "points"=>"10");
$achievements[964]=array("title"=>"Mark of the Holt: B", "points"=>"5");
$achievements[965]=array("title"=>"Mark of the Desert: B", "points"=>"5");
$achievements[966]=array("title"=>"Mark of the Sea: B", "points"=>"5");
$achievements[967]=array("title"=>"Mark of the Lake: B", "points"=>"5");
$achievements[968]=array("title"=>"On Your Mark: B", "points"=>"10");
$achievements[969]=array("title"=>"Mark of the Holt: A", "points"=>"5");
$achievements[970]=array("title"=>"Mark of the Desert: A", "points"=>"5");
$achievements[971]=array("title"=>"Mark of the Sea: A", "points"=>"5");
$achievements[972]=array("title"=>"Mark of the Lake: A", "points"=>"5");
$achievements[973]=array("title"=>"On Your Mark: A", "points"=>"10");
$achievements[974]=array("title"=>"Mark of the Holt: S", "points"=>"5");
$achievements[975]=array("title"=>"Mark of the Desert: S", "points"=>"5");
$achievements[976]=array("title"=>"Mark of the Sea: S", "points"=>"5");
$achievements[977]=array("title"=>"Mark of the Lake: S", "points"=>"5");
$achievements[978]=array("title"=>"On Your Mark: S", "points"=>"10");
$achievements[979]=array("title"=>"Bring Your B Game I", "points"=>"5");
$achievements[980]=array("title"=>"Bring Your B Game II", "points"=>"5");
$achievements[981]=array("title"=>"Bring Your B Game III", "points"=>"5");
$achievements[982]=array("title"=>"Straight Bs", "points"=>"10");
$achievements[983]=array("title"=>"Bring Your A Game I", "points"=>"5");
$achievements[984]=array("title"=>"Bring Your A Game II", "points"=>"5");
$achievements[985]=array("title"=>"Bring Your A Game III", "points"=>"5");
$achievements[986]=array("title"=>"Straight As", "points"=>"10");
$achievements[987]=array("title"=>"Bring Your S Game I", "points"=>"5");
$achievements[988]=array("title"=>"Bring Your S Game II", "points"=>"5");
$achievements[989]=array("title"=>"Bring Your S Game III", "points"=>"5");
$achievements[990]=array("title"=>"Straight Ss", "points"=>"10");
$achievements[878]=array("title"=>"I Can Dig It I", "points"=>"5");
$achievements[879]=array("title"=>"I Can Dig It II", "points"=>"5");
$achievements[880]=array("title"=>"I Can Dig It III", "points"=>"5");
$achievements[881]=array("title"=>"I Can Dig It IV", "points"=>"10");
$achievements[882]=array("title"=>"No Stone Unturned", "points"=>"20");
$achievements[1019]=array("title"=>"Unhide and Seek", "points"=>"20");
$achievements[44]=array("title"=>"Mastering War", "points"=>"20");
$achievements[55]=array("title"=>"Mastering Magic", "points"=>"20");
$achievements[56]=array("title"=>"A Life of Adventure", "points"=>"30");
$achievements[97]=array("title"=>"Mastering the Hand", "points"=>"20");
$achievements[113]=array("title"=>"Mastering the Land", "points"=>"20");
$achievements[912]=array("title"=>"Can't Someone Else Do It I", "points"=>"5");
$achievements[913]=array("title"=>"Can't Someone Else Do It II", "points"=>"5");
$achievements[914]=array("title"=>"Can't Someone Else Do It III", "points"=>"10");
$achievements[915]=array("title"=>"Nothing Ventured, Nothing Gained", "points"=>"20");
$achievements[928]=array("title"=>"Out of Sight", "points"=>"5");
$achievements[929]=array("title"=>"Out of Sight Out of Mind", "points"=>"10");
$achievements[1020]=array("title"=>"Breaking Bo", "points"=>"5");
$achievements[19]=array("title"=>"Stick Them with the Pointy End I", "points"=>"5");
$achievements[20]=array("title"=>"Stick Them with the Pointy End II", "points"=>"5");
$achievements[21]=array("title"=>"Stick Them with the Pointy End III", "points"=>"5");
$achievements[22]=array("title"=>"Stick Them with the Pointy End IV", "points"=>"5");
$achievements[23]=array("title"=>"Stick Them with the Pointy End V", "points"=>"5");
$achievements[24]=array("title"=>"The Sweet Science I", "points"=>"5");
$achievements[25]=array("title"=>"The Sweet Science II", "points"=>"5");
$achievements[26]=array("title"=>"The Sweet Science III", "points"=>"5");
$achievements[27]=array("title"=>"The Sweet Science IV", "points"=>"5");
$achievements[28]=array("title"=>"The Sweet Science V", "points"=>"5");
$achievements[29]=array("title"=>"An Axe to Grind I", "points"=>"5");
$achievements[30]=array("title"=>"An Axe to Grind II", "points"=>"5");
$achievements[31]=array("title"=>"An Axe to Grind III", "points"=>"5");
$achievements[32]=array("title"=>"An Axe to Grind IV", "points"=>"5");
$achievements[33]=array("title"=>"An Axe to Grind V", "points"=>"5");
$achievements[34]=array("title"=>"Strong Lance Arm I", "points"=>"5");
$achievements[35]=array("title"=>"Strong Lance Arm II", "points"=>"5");
$achievements[36]=array("title"=>"Strong Lance Arm III", "points"=>"5");
$achievements[37]=array("title"=>"Strong Lance Arm IV", "points"=>"5");
$achievements[38]=array("title"=>"Strong Lance Arm V", "points"=>"5");
$achievements[39]=array("title"=>"Just Talkin' 'bout Shafts I", "points"=>"5");
$achievements[40]=array("title"=>"Just Talkin' 'bout Shafts II", "points"=>"5");
$achievements[41]=array("title"=>"Just Talkin' 'bout Shafts III", "points"=>"5");
$achievements[42]=array("title"=>"Just Talkin' 'bout Shafts IV", "points"=>"5");
$achievements[43]=array("title"=>"Just Talkin' 'bout Shafts V", "points"=>"5");
$achievements[45]=array("title"=>"I Got the Magic Stick I", "points"=>"5");
$achievements[46]=array("title"=>"I Got the Magic Stick II", "points"=>"5");
$achievements[47]=array("title"=>"I Got the Magic Stick III", "points"=>"5");
$achievements[48]=array("title"=>"I Got the Magic Stick IV", "points"=>"5");
$achievements[49]=array("title"=>"I Got the Magic Stick V", "points"=>"5");
$achievements[50]=array("title"=>"Bring Out Your Dead I", "points"=>"5");
$achievements[51]=array("title"=>"Bring Out Your Dead II", "points"=>"5");
$achievements[52]=array("title"=>"Bring Out Your Dead III", "points"=>"5");
$achievements[53]=array("title"=>"Bring Out Your Dead IV", "points"=>"5");
$achievements[54]=array("title"=>"Bring Out Your Dead V", "points"=>"5");
$achievements[592]=array("title"=>"Through the Gate I", "points"=>"5");
$achievements[593]=array("title"=>"Through the Gate II", "points"=>"5");
$achievements[594]=array("title"=>"Through the Gate III", "points"=>"5");
$achievements[595]=array("title"=>"Through the Gate IV", "points"=>"5");
$achievements[596]=array("title"=>"Through the Gate V", "points"=>"5");
$achievements[57]=array("title"=>"Knock on Wood I", "points"=>"5");
$achievements[58]=array("title"=>"Knock on Wood II", "points"=>"5");
$achievements[59]=array("title"=>"Knock on Wood III", "points"=>"5");
$achievements[60]=array("title"=>"Knock on Wood IV", "points"=>"5");
$achievements[61]=array("title"=>"Knock on Wood V", "points"=>"5");
$achievements[62]=array("title"=>"Temper, Temper I", "points"=>"5");
$achievements[63]=array("title"=>"Temper, Temper II", "points"=>"5");
$achievements[64]=array("title"=>"Temper, Temper III", "points"=>"5");
$achievements[65]=array("title"=>"Temper, Temper IV", "points"=>"5");
$achievements[66]=array("title"=>"Temper, Temper V", "points"=>"5");
$achievements[67]=array("title"=>"The Riddle of Steel I", "points"=>"5");
$achievements[68]=array("title"=>"The Riddle of Steel II", "points"=>"5");
$achievements[69]=array("title"=>"The Riddle of Steel III", "points"=>"5");
$achievements[70]=array("title"=>"The Riddle of Steel IV", "points"=>"5");
$achievements[71]=array("title"=>"The Riddle of Steel V", "points"=>"5");
$achievements[72]=array("title"=>"Heart of Gold I", "points"=>"5");
$achievements[73]=array("title"=>"Heart of Gold II", "points"=>"5");
$achievements[74]=array("title"=>"Heart of Gold III", "points"=>"5");
$achievements[75]=array("title"=>"Heart of Gold IV", "points"=>"5");
$achievements[76]=array("title"=>"Heart of Gold V", "points"=>"5");
$achievements[77]=array("title"=>"Tougher than Leather I", "points"=>"5");
$achievements[78]=array("title"=>"Tougher than Leather II", "points"=>"5");
$achievements[79]=array("title"=>"Tougher than Leather III", "points"=>"5");
$achievements[80]=array("title"=>"Tougher than Leather IV", "points"=>"5");
$achievements[81]=array("title"=>"Tougher than Leather V", "points"=>"5");
$achievements[82]=array("title"=>"Smiling, Styling, and Textiling I", "points"=>"5");
$achievements[83]=array("title"=>"Smiling, Styling, and Textiling II", "points"=>"5");
$achievements[84]=array("title"=>"Smiling, Styling, and Textiling III", "points"=>"5");
$achievements[85]=array("title"=>"Smiling, Styling, and Textiling IV", "points"=>"5");
$achievements[86]=array("title"=>"Smiling, Styling, and Textiling V", "points"=>"5");
$achievements[87]=array("title"=>"'Tis True without Lying I", "points"=>"5");
$achievements[88]=array("title"=>"'Tis True without Lying II", "points"=>"5");
$achievements[89]=array("title"=>"'Tis True without Lying III", "points"=>"5");
$achievements[90]=array("title"=>"'Tis True without Lying IV", "points"=>"5");
$achievements[91]=array("title"=>"'Tis True without Lying V", "points"=>"5");
$achievements[92]=array("title"=>"All in Good Taste I", "points"=>"5");
$achievements[93]=array("title"=>"All in Good Taste II", "points"=>"5");
$achievements[94]=array("title"=>"All in Good Taste III", "points"=>"5");
$achievements[95]=array("title"=>"All in Good Taste IV", "points"=>"5");
$achievements[96]=array("title"=>"All in Good Taste V", "points"=>"5");
$achievements[98]=array("title"=>"Breaking Rocks in the Hot Sun I", "points"=>"5");
$achievements[99]=array("title"=>"Breaking Rocks in the Hot Sun II", "points"=>"5");
$achievements[100]=array("title"=>"Breaking Rocks in the Hot Sun III", "points"=>"5");
$achievements[101]=array("title"=>"Breaking Rocks in the Hot Sun IV", "points"=>"5");
$achievements[102]=array("title"=>"Breaking Rocks in the Hot Sun V", "points"=>"5");
$achievements[103]=array("title"=>"Fear the Reaper I", "points"=>"5");
$achievements[104]=array("title"=>"Fear the Reaper II", "points"=>"5");
$achievements[105]=array("title"=>"Fear the Reaper III", "points"=>"5");
$achievements[106]=array("title"=>"Fear the Reaper IV", "points"=>"5");
$achievements[107]=array("title"=>"Fear the Reaper V", "points"=>"5");
$achievements[108]=array("title"=>"Gone Fishin' I", "points"=>"5");
$achievements[109]=array("title"=>"Gone Fishin' II", "points"=>"5");
$achievements[110]=array("title"=>"Gone Fishin' III", "points"=>"5");
$achievements[111]=array("title"=>"Gone Fishin' IV", "points"=>"5");
$achievements[112]=array("title"=>"Gone Fishin' V", "points"=>"5");
$achievements[813]=array("title"=>"Cutting Your Wolf Loose: Maelstrom I", "points"=>"5");
$achievements[814]=array("title"=>"Cutting Your Wolf Loose: Maelstrom II", "points"=>"5");
$achievements[815]=array("title"=>"Cutting Your Wolf Loose: Maelstrom III", "points"=>"5");
$achievements[816]=array("title"=>"Cutting Your Wolf Loose: Maelstrom IV", "points"=>"5");
$achievements[817]=array("title"=>"Cutting Your Wolf Loose: Maelstrom V", "points"=>"5");
$achievements[833]=array("title"=>"Cutting Your Wolf Loose: Twin Adder I", "points"=>"5");
$achievements[834]=array("title"=>"Cutting Your Wolf Loose: Twin Adder II", "points"=>"5");
$achievements[835]=array("title"=>"Cutting Your Wolf Loose: Twin Adder III", "points"=>"5");
$achievements[836]=array("title"=>"Cutting Your Wolf Loose: Twin Adder IV", "points"=>"5");
$achievements[837]=array("title"=>"Cutting Your Wolf Loose: Twin Adder V", "points"=>"5");
$achievements[823]=array("title"=>"Cutting Your Wolf Loose: Immortal Flames I", "points"=>"5");
$achievements[824]=array("title"=>"Cutting Your Wolf Loose: Immortal Flames II", "points"=>"5");
$achievements[825]=array("title"=>"Cutting Your Wolf Loose: Immortal Flames III", "points"=>"5");
$achievements[826]=array("title"=>"Cutting Your Wolf Loose: Immortal Flames IV", "points"=>"5");
$achievements[827]=array("title"=>"Cutting Your Wolf Loose: Immortal Flames V", "points"=>"5");
$achievements[858]=array("title"=>"Leaving a Good Impression I", "points"=>"0");
$achievements[859]=array("title"=>"Leaving a Good Impression II", "points"=>"0");
$achievements[860]=array("title"=>"Leaving a Good Impression III", "points"=>"0");
$achievements[861]=array("title"=>"Leaving a Good Impression IV", "points"=>"0");
$achievements[862]=array("title"=>"Everybody's Darling", "points"=>"0");
$achievements[126]=array("title"=>"My Body Is a Temple", "points"=>"5");
$achievements[127]=array("title"=>"Dress Like a Pirate Day", "points"=>"5");
$achievements[128]=array("title"=>"A Mummer in Motley", "points"=>"5");
$achievements[129]=array("title"=>"Raising the Curtana", "points"=>"10");
$achievements[130]=array("title"=>"Enter the Coeurl", "points"=>"10");
$achievements[131]=array("title"=>"Cleaving to Tradition", "points"=>"10");
$achievements[132]=array("title"=>"Having a Gae Old Time", "points"=>"10");
$achievements[133]=array("title"=>"Hard to Miss", "points"=>"10");
$achievements[134]=array("title"=>"Dressed to Heal", "points"=>"10");
$achievements[135]=array("title"=>"Ohohohohoho!", "points"=>"10");
$achievements[597]=array("title"=>"Green Eyes", "points"=>"10");
$achievements[598]=array("title"=>"The Reader", "points"=>"10");
$achievements[136]=array("title"=>"Armed to the Teeth", "points"=>"30");
$achievements[925]=array("title"=>"Taking It to the Stars", "points"=>"10");
$achievements[926]=array("title"=>"A Star Is Born", "points"=>"10");
$achievements[1028]=array("title"=>"Inspire the Nexus", "points"=>"10");
$achievements[114]=array("title"=>"On the Payroll I", "points"=>"5");
$achievements[115]=array("title"=>"On the Payroll II", "points"=>"5");
$achievements[116]=array("title"=>"On the Payroll III", "points"=>"5");
$achievements[117]=array("title"=>"On the Payroll IV", "points"=>"5");
$achievements[118]=array("title"=>"On the Payroll V", "points"=>"5");
$achievements[119]=array("title"=>"Who Wants to Be a Gillionaire?", "points"=>"10");
$achievements[1006]=array("title"=>"Break It Down I", "points"=>"5");
$achievements[1007]=array("title"=>"Break It Down II", "points"=>"5");
$achievements[1008]=array("title"=>"Break It Down III", "points"=>"5");
$achievements[1009]=array("title"=>"Break It Down IV", "points"=>"5");
$achievements[1010]=array("title"=>"Break It Down V", "points"=>"10");
$achievements[1011]=array("title"=>"You're Tearing Me Apart", "points"=>"10");
$achievements[296]=array("title"=>"Getting Too Attached I", "points"=>"5");
$achievements[297]=array("title"=>"Getting Too Attached II", "points"=>"5");
$achievements[298]=array("title"=>"Getting Too Attached III", "points"=>"5");
$achievements[299]=array("title"=>"Getting Too Attached IV", "points"=>"5");
$achievements[300]=array("title"=>"Materia Hysteria", "points"=>"10");
$achievements[301]=array("title"=>"Beginner's Luck", "points"=>"10");
$achievements[302]=array("title"=>"I Make My Own Luck", "points"=>"20");
$achievements[303]=array("title"=>"Luck's Got Nothing to Do with It", "points"=>"30");
$achievements[304]=array("title"=>"I Got This!", "points"=>"40");
$achievements[305]=array("title"=>"Prepare to Be Assimilated I", "points"=>"5");
$achievements[306]=array("title"=>"Prepare to Be Assimilated II", "points"=>"5");
$achievements[307]=array("title"=>"Prepare to Be Assimilated III", "points"=>"5");
$achievements[308]=array("title"=>"Prepare to Be Assimilated IV", "points"=>"5");
$achievements[309]=array("title"=>"Living in a Materia World", "points"=>"10");
$achievements[927]=array("title"=>"I Got a Good Materia", "points"=>"10");
$achievements[137]=array("title"=>"Going with the Grain: Amateur", "points"=>"5");
$achievements[138]=array("title"=>"Going with the Grain: Initiate", "points"=>"5");
$achievements[139]=array("title"=>"Going with the Grain: Apprentice", "points"=>"5");
$achievements[140]=array("title"=>"Going with the Grain: Journeyman", "points"=>"5");
$achievements[141]=array("title"=>"Going with the Grain: Artisan", "points"=>"10");
$achievements[142]=array("title"=>"A Carpenter's Life for Me", "points"=>"30");
$achievements[695]=array("title"=>"I Made That: Carpenter I", "points"=>"5");
$achievements[696]=array("title"=>"I Made That: Carpenter II", "points"=>"5");
$achievements[697]=array("title"=>"I Made That: Carpenter III", "points"=>"10");
$achievements[750]=array("title"=>"An Eye for Detail: Carpenter I", "points"=>"5");
$achievements[751]=array("title"=>"An Eye for Detail: Carpenter II", "points"=>"5");
$achievements[752]=array("title"=>"An Eye for Detail: Carpenter III", "points"=>"10");
$achievements[143]=array("title"=>"Working the Bellows: Amateur", "points"=>"5");
$achievements[144]=array("title"=>"Working the Bellows: Initiate", "points"=>"5");
$achievements[145]=array("title"=>"Working the Bellows: Apprentice", "points"=>"5");
$achievements[146]=array("title"=>"Working the Bellows: Journeyman", "points"=>"5");
$achievements[147]=array("title"=>"Working the Bellows: Artisan", "points"=>"10");
$achievements[148]=array("title"=>"A Blacksmith's Life for Me", "points"=>"30");
$achievements[698]=array("title"=>"I Made That: Blacksmith I", "points"=>"5");
$achievements[699]=array("title"=>"I Made That: Blacksmith II", "points"=>"5");
$achievements[700]=array("title"=>"I Made That: Blacksmith III", "points"=>"10");
$achievements[753]=array("title"=>"An Eye for Detail: Blacksmith I", "points"=>"5");
$achievements[754]=array("title"=>"An Eye for Detail: Blacksmith II", "points"=>"5");
$achievements[755]=array("title"=>"An Eye for Detail: Blacksmith III", "points"=>"10");
$achievements[149]=array("title"=>"Pounding Out the Dents: Amateur", "points"=>"5");
$achievements[150]=array("title"=>"Pounding Out the Dents: Initiate", "points"=>"5");
$achievements[151]=array("title"=>"Pounding Out the Dents: Apprentice", "points"=>"5");
$achievements[152]=array("title"=>"Pounding Out the Dents: Journeyman", "points"=>"5");
$achievements[153]=array("title"=>"Pounding Out the Dents: Artisan", "points"=>"10");
$achievements[154]=array("title"=>"An Armorer's Life for Me", "points"=>"30");
$achievements[701]=array("title"=>"I Made That: Armorer I", "points"=>"5");
$achievements[702]=array("title"=>"I Made That: Armorer II", "points"=>"5");
$achievements[703]=array("title"=>"I Made That: Armorer III", "points"=>"10");
$achievements[756]=array("title"=>"An Eye for Detail: Armorer I", "points"=>"5");
$achievements[757]=array("title"=>"An Eye for Detail: Armorer II", "points"=>"5");
$achievements[758]=array("title"=>"An Eye for Detail: Armorer III", "points"=>"10");
$achievements[155]=array("title"=>"Cutting the Carats: Amateur", "points"=>"5");
$achievements[156]=array("title"=>"Cutting the Carats: Initiate", "points"=>"5");
$achievements[157]=array("title"=>"Cutting the Carats: Apprentice", "points"=>"5");
$achievements[158]=array("title"=>"Cutting the Carats: Journeyman", "points"=>"5");
$achievements[159]=array("title"=>"Cutting the Carats: Artisan", "points"=>"10");
$achievements[160]=array("title"=>"A Goldsmith's Life for Me", "points"=>"30");
$achievements[704]=array("title"=>"I Made That: Goldsmith I", "points"=>"5");
$achievements[705]=array("title"=>"I Made That: Goldsmith II", "points"=>"5");
$achievements[706]=array("title"=>"I Made That: Goldsmith III", "points"=>"10");
$achievements[759]=array("title"=>"An Eye for Detail: Goldsmith I", "points"=>"5");
$achievements[760]=array("title"=>"An Eye for Detail: Goldsmith II", "points"=>"5");
$achievements[761]=array("title"=>"An Eye for Detail: Goldsmith III", "points"=>"10");
$achievements[161]=array("title"=>"Hiding in Plain Sight: Amateur", "points"=>"5");
$achievements[162]=array("title"=>"Hiding in Plain Sight: Initiate", "points"=>"5");
$achievements[163]=array("title"=>"Hiding in Plain Sight: Apprentice", "points"=>"5");
$achievements[164]=array("title"=>"Hiding in Plain Sight: Journeyman", "points"=>"5");
$achievements[165]=array("title"=>"Hiding in Plain Sight: Artisan", "points"=>"10");
$achievements[166]=array("title"=>"A Leatherworker's Life for Me", "points"=>"30");
$achievements[707]=array("title"=>"I Made That: Leatherworker I", "points"=>"5");
$achievements[708]=array("title"=>"I Made That: Leatherworker II", "points"=>"5");
$achievements[709]=array("title"=>"I Made That: Leatherworker III", "points"=>"10");
$achievements[762]=array("title"=>"An Eye for Detail: Leatherworker I", "points"=>"5");
$achievements[763]=array("title"=>"An Eye for Detail: Leatherworker II", "points"=>"5");
$achievements[764]=array("title"=>"An Eye for Detail: Leatherworker III", "points"=>"10");
$achievements[167]=array("title"=>"Threading the Needle: Amateur", "points"=>"5");
$achievements[168]=array("title"=>"Threading the Needle: Initiate", "points"=>"5");
$achievements[169]=array("title"=>"Threading the Needle: Apprentice", "points"=>"5");
$achievements[170]=array("title"=>"Threading the Needle: Journeyman", "points"=>"5");
$achievements[171]=array("title"=>"Threading the Needle: Artisan", "points"=>"10");
$achievements[172]=array("title"=>"A Weaver's Life for Me", "points"=>"30");
$achievements[710]=array("title"=>"I Made That: Weaver I", "points"=>"5");
$achievements[711]=array("title"=>"I Made That: Weaver II", "points"=>"5");
$achievements[712]=array("title"=>"I Made That: Weaver III", "points"=>"10");
$achievements[765]=array("title"=>"An Eye for Detail: Weaver I", "points"=>"5");
$achievements[766]=array("title"=>"An Eye for Detail: Weaver II", "points"=>"5");
$achievements[767]=array("title"=>"An Eye for Detail: Weaver III", "points"=>"10");
$achievements[173]=array("title"=>"Mixing It Up: Amateur", "points"=>"5");
$achievements[174]=array("title"=>"Mixing It Up: Initiate", "points"=>"5");
$achievements[175]=array("title"=>"Mixing It Up: Apprentice", "points"=>"5");
$achievements[176]=array("title"=>"Mixing It Up: Journeyman", "points"=>"5");
$achievements[177]=array("title"=>"Mixing It Up: Artisan", "points"=>"10");
$achievements[178]=array("title"=>"An Alchemist's Life for Me", "points"=>"30");
$achievements[713]=array("title"=>"I Made That: Alchemist I", "points"=>"5");
$achievements[714]=array("title"=>"I Made That: Alchemist II", "points"=>"5");
$achievements[715]=array("title"=>"I Made That: Alchemist III", "points"=>"10");
$achievements[768]=array("title"=>"An Eye for Detail: Alchemist I", "points"=>"5");
$achievements[769]=array("title"=>"An Eye for Detail: Alchemist II", "points"=>"5");
$achievements[770]=array("title"=>"An Eye for Detail: Alchemist III", "points"=>"10");
$achievements[179]=array("title"=>"Savoring the Realm: Amateur", "points"=>"5");
$achievements[180]=array("title"=>"Savoring the Realm: Initiate", "points"=>"5");
$achievements[181]=array("title"=>"Savoring the Realm: Apprentice", "points"=>"5");
$achievements[182]=array("title"=>"Savoring the Realm: Journeyman", "points"=>"5");
$achievements[183]=array("title"=>"Savoring the Realm: Artisan", "points"=>"10");
$achievements[184]=array("title"=>"A Life of Cooking", "points"=>"30");
$achievements[716]=array("title"=>"I Made That: Culinarian I", "points"=>"5");
$achievements[717]=array("title"=>"I Made That: Culinarian II", "points"=>"5");
$achievements[718]=array("title"=>"I Made That: Culinarian III", "points"=>"10");
$achievements[771]=array("title"=>"An Eye for Detail: Culinarian I", "points"=>"5");
$achievements[772]=array("title"=>"An Eye for Detail: Culinarian II", "points"=>"5");
$achievements[773]=array("title"=>"An Eye for Detail: Culinarian III", "points"=>"10");
$achievements[185]=array("title"=>"Mining Your Own Business: La Noscea I", "points"=>"5");
$achievements[186]=array("title"=>"Mining Your Own Business: La Noscea II", "points"=>"5");
$achievements[187]=array("title"=>"Mining Your Own Business: La Noscea III", "points"=>"5");
$achievements[188]=array("title"=>"Mining Your Own Business: La Noscea IV", "points"=>"5");
$achievements[189]=array("title"=>"Mining Your Own Business: La Noscea V", "points"=>"5");
$achievements[190]=array("title"=>"A Miner's Life for Me: La Noscea", "points"=>"10");
$achievements[191]=array("title"=>"Mining Your Own Business: Black Shroud I", "points"=>"5");
$achievements[192]=array("title"=>"Mining Your Own Business: Black Shroud II", "points"=>"5");
$achievements[193]=array("title"=>"Mining Your Own Business: Black Shroud III", "points"=>"5");
$achievements[194]=array("title"=>"Mining Your Own Business: Black Shroud IV", "points"=>"5");
$achievements[195]=array("title"=>"Mining Your Own Business: Black Shroud V", "points"=>"5");
$achievements[196]=array("title"=>"A Miner's Life for Me: Black Shroud", "points"=>"10");
$achievements[197]=array("title"=>"Mining Your Own Business: Thanalan I", "points"=>"5");
$achievements[198]=array("title"=>"Mining Your Own Business: Thanalan II", "points"=>"5");
$achievements[199]=array("title"=>"Mining Your Own Business: Thanalan III", "points"=>"5");
$achievements[200]=array("title"=>"Mining Your Own Business: Thanalan IV", "points"=>"5");
$achievements[201]=array("title"=>"Mining Your Own Business: Thanalan V", "points"=>"5");
$achievements[202]=array("title"=>"A Miner's Life for Me: Thanalan", "points"=>"10");
$achievements[203]=array("title"=>"A Miner's Life for Me: Eorzea", "points"=>"30");
$achievements[719]=array("title"=>"I Found That: Miner I", "points"=>"5");
$achievements[720]=array("title"=>"I Found That: Miner II", "points"=>"5");
$achievements[721]=array("title"=>"I Found That: Miner III", "points"=>"10");
$achievements[774]=array("title"=>"An Eye for Quality: Miner I", "points"=>"5");
$achievements[775]=array("title"=>"An Eye for Quality: Miner II", "points"=>"5");
$achievements[776]=array("title"=>"An Eye for Quality: Miner III", "points"=>"10");
$achievements[222]=array("title"=>"Logging the Hours: La Noscea I", "points"=>"5");
$achievements[223]=array("title"=>"Logging the Hours: La Noscea II", "points"=>"5");
$achievements[224]=array("title"=>"Logging the Hours: La Noscea III", "points"=>"5");
$achievements[225]=array("title"=>"Logging the Hours: La Noscea IV", "points"=>"5");
$achievements[226]=array("title"=>"Logging the Hours: La Noscea V", "points"=>"5");
$achievements[227]=array("title"=>"A Botanist's Life for Me: La Noscea", "points"=>"10");
$achievements[228]=array("title"=>"Logging the Hours: Black Shroud I", "points"=>"5");
$achievements[229]=array("title"=>"Logging the Hours: Black Shroud II", "points"=>"5");
$achievements[230]=array("title"=>"Logging the Hours: Black Shroud III", "points"=>"5");
$achievements[231]=array("title"=>"Logging the Hours: Black Shroud IV", "points"=>"5");
$achievements[232]=array("title"=>"Logging the Hours: Black Shroud V", "points"=>"5");
$achievements[233]=array("title"=>"A Botanist's Life for Me: Black Shroud", "points"=>"10");
$achievements[234]=array("title"=>"Logging the Hours: Thanalan I", "points"=>"5");
$achievements[235]=array("title"=>"Logging the Hours: Thanalan II", "points"=>"5");
$achievements[236]=array("title"=>"Logging the Hours: Thanalan III", "points"=>"5");
$achievements[237]=array("title"=>"Logging the Hours: Thanalan IV", "points"=>"5");
$achievements[238]=array("title"=>"Logging the Hours: Thanalan V", "points"=>"5");
$achievements[239]=array("title"=>"A Botanist's Life for Me: Thanalan", "points"=>"10");
$achievements[240]=array("title"=>"A Botanist's Life for Me: Eorzea", "points"=>"30");
$achievements[722]=array("title"=>"I Found That: Botanist I", "points"=>"5");
$achievements[723]=array("title"=>"I Found That: Botanist II", "points"=>"5");
$achievements[724]=array("title"=>"I Found That: Botanist III", "points"=>"10");
$achievements[777]=array("title"=>"An Eye for Quality: Botanist I", "points"=>"5");
$achievements[778]=array("title"=>"An Eye for Quality: Botanist II", "points"=>"5");
$achievements[779]=array("title"=>"An Eye for Quality: Botanist III", "points"=>"10");
$achievements[259]=array("title"=>"Good Things Come to Those Who Bait: La Noscea I", "points"=>"5");
$achievements[260]=array("title"=>"Good Things Come to Those Who Bait: La Noscea II", "points"=>"5");
$achievements[261]=array("title"=>"Good Things Come to Those Who Bait: La Noscea III", "points"=>"5");
$achievements[262]=array("title"=>"Good Things Come to Those Who Bait: La Noscea IV", "points"=>"5");
$achievements[263]=array("title"=>"Good Things Come to Those Who Bait: La Noscea V", "points"=>"5");
$achievements[264]=array("title"=>"A Fisher's Life for Me: La Noscea", "points"=>"10");
$achievements[265]=array("title"=>"Good Things Come to Those Who Bait: Black Shroud I", "points"=>"5");
$achievements[266]=array("title"=>"Good Things Come to Those Who Bait: Black Shroud II", "points"=>"5");
$achievements[267]=array("title"=>"Good Things Come to Those Who Bait: Black Shroud III", "points"=>"5");
$achievements[268]=array("title"=>"Good Things Come to Those Who Bait: Black Shroud IV", "points"=>"5");
$achievements[269]=array("title"=>"Good Things Come to Those Who Bait: Black Shroud V", "points"=>"5");
$achievements[270]=array("title"=>"A Fisher's Life for Me: Black Shroud", "points"=>"10");
$achievements[271]=array("title"=>"Good Things Come to Those Who Bait: Thanalan I", "points"=>"5");
$achievements[272]=array("title"=>"Good Things Come to Those Who Bait: Thanalan II", "points"=>"5");
$achievements[273]=array("title"=>"Good Things Come to Those Who Bait: Thanalan III", "points"=>"5");
$achievements[274]=array("title"=>"Good Things Come to Those Who Bait: Thanalan IV", "points"=>"5");
$achievements[275]=array("title"=>"Good Things Come to Those Who Bait: Thanalan V", "points"=>"5");
$achievements[276]=array("title"=>"A Fisher's Life for Me: Thanalan", "points"=>"10");
$achievements[277]=array("title"=>"A Fisher's Life for Me: Eorzea", "points"=>"30");
$achievements[725]=array("title"=>"I Caught That I", "points"=>"5");
$achievements[726]=array("title"=>"I Caught That II", "points"=>"5");
$achievements[727]=array("title"=>"I Caught That III", "points"=>"10");
$achievements[780]=array("title"=>"The One that Didn't Get Away I", "points"=>"5");
$achievements[781]=array("title"=>"The One that Didn't Get Away II", "points"=>"5");
$achievements[782]=array("title"=>"The One that Didn't Get Away III", "points"=>"10");
$achievements[916]=array("title"=>"Go Big or Go Home I", "points"=>"5");
$achievements[917]=array("title"=>"Go Big or Go Home II", "points"=>"10");
$achievements[918]=array("title"=>"Go Big or Go Home III", "points"=>"20");
$achievements[1015]=array("title"=>"Go Big or Go Home IV", "points"=>"20");
$achievements[1016]=array("title"=>"Go Big or Go Home V", "points"=>"20");
$achievements[1017]=array("title"=>"Go Big or Go Home VI", "points"=>"20");
$achievements[1018]=array("title"=>"Go Big or Go Home VII", "points"=>"20");
$achievements[341]=array("title"=>"Serving a Greater Cause I", "points"=>"5");
$achievements[342]=array("title"=>"Serving a Greater Cause II", "points"=>"5");
$achievements[343]=array("title"=>"Serving a Greater Cause III", "points"=>"5");
$achievements[344]=array("title"=>"Serving a Greater Cause IV", "points"=>"5");
$achievements[345]=array("title"=>"Serving a Greater Cause V", "points"=>"5");
$achievements[346]=array("title"=>"Serving a Greater Cause VI", "points"=>"10");
$achievements[347]=array("title"=>"Enraptured Servitude", "points"=>"20");
$achievements[644]=array("title"=>"Father Knows Hest I", "points"=>"5");
$achievements[645]=array("title"=>"Father Knows Hest II", "points"=>"5");
$achievements[646]=array("title"=>"Father Knows Hest III", "points"=>"10");
$achievements[310]=array("title"=>"Leaving Limsa Lominsa", "points"=>"5");
$achievements[311]=array("title"=>"Gone from Gridania", "points"=>"5");
$achievements[312]=array("title"=>"Out of Ul'dah", "points"=>"5");
$achievements[783]=array("title"=>"Back from the Wood", "points"=>"5");
$achievements[784]=array("title"=>"Skeletons", "points"=>"5");
$achievements[785]=array("title"=>"Those Who Wait", "points"=>"5");
$achievements[786]=array("title"=>"History Repeating", "points"=>"5");
$achievements[787]=array("title"=>"Free Wing Night", "points"=>"10");
$achievements[788]=array("title"=>"Warrior of Light", "points"=>"20");
$achievements[898]=array("title"=>"A Realm Awoken", "points"=>"20");
$achievements[899]=array("title"=>"Through the Maelstrom", "points"=>"20");
$achievements[900]=array("title"=>"The Truth Is Down There", "points"=>"10");
$achievements[901]=array("title"=>"You Can Handle the Truth", "points"=>"20");
$achievements[902]=array("title"=>"I Like Big Fish and I Cannot Lie", "points"=>"10");
$achievements[789]=array("title"=>"Storyteller I", "points"=>"5");
$achievements[790]=array("title"=>"Storyteller II", "points"=>"10");
$achievements[791]=array("title"=>"Storyteller III", "points"=>"20");
$achievements[313]=array("title"=>"This One Time, at Level Thirty...", "points"=>"5");
$achievements[314]=array("title"=>"Tales of War", "points"=>"10");
$achievements[315]=array("title"=>"Tales of Magic", "points"=>"10");
$achievements[316]=array("title"=>"Tales of the Hand", "points"=>"10");
$achievements[317]=array("title"=>"Tales of the Land", "points"=>"10");
$achievements[318]=array("title"=>"The Greatest Tales Ever Told", "points"=>"20");
$achievements[407]=array("title"=>"Like a Knight in Shining Armor", "points"=>"5");
$achievements[408]=array("title"=>"Bulletproof", "points"=>"5");
$achievements[409]=array("title"=>"I Am the Warrior", "points"=>"5");
$achievements[410]=array("title"=>"Dragoon Age", "points"=>"5");
$achievements[411]=array("title"=>"A Bard's Tale", "points"=>"5");
$achievements[412]=array("title"=>"Seeing White", "points"=>"5");
$achievements[413]=array("title"=>"Back in Black", "points"=>"5");
$achievements[599]=array("title"=>"Soul Summoner", "points"=>"5");
$achievements[600]=array("title"=>"Flying Colors", "points"=>"5");
$achievements[414]=array("title"=>"Career Opportunities", "points"=>"20");
$achievements[1001]=array("title"=>"Eorzea Defended", "points"=>"20");
$achievements[1004]=array("title"=>"The Postmoogle Always Rings Twice", "points"=>"10");
$achievements[1005]=array("title"=>"The Rest of the Story", "points"=>"10");
$achievements[608]=array("title"=>"Uphill Battle I", "points"=>"5");
$achievements[609]=array("title"=>"Uphill Battle II", "points"=>"5");
$achievements[610]=array("title"=>"Uphill Battle III", "points"=>"10");
$achievements[611]=array("title"=>"With Saw in Hand I", "points"=>"5");
$achievements[612]=array("title"=>"With Saw in Hand II", "points"=>"5");
$achievements[613]=array("title"=>"With Saw in Hand III", "points"=>"10");
$achievements[614]=array("title"=>"With Hammer in Hand I", "points"=>"5");
$achievements[615]=array("title"=>"With Hammer in Hand II", "points"=>"5");
$achievements[616]=array("title"=>"With Hammer in Hand III", "points"=>"10");
$achievements[617]=array("title"=>"With Steel in Hand I", "points"=>"5");
$achievements[618]=array("title"=>"With Steel in Hand II", "points"=>"5");
$achievements[619]=array("title"=>"With Steel in Hand III", "points"=>"10");
$achievements[620]=array("title"=>"With Gem in Hand I", "points"=>"5");
$achievements[621]=array("title"=>"With Gem in Hand II", "points"=>"5");
$achievements[622]=array("title"=>"With Gem in Hand III", "points"=>"10");
$achievements[623]=array("title"=>"With Skin in Hand I", "points"=>"5");
$achievements[624]=array("title"=>"With Skin in Hand II", "points"=>"5");
$achievements[625]=array("title"=>"With Skin in Hand III", "points"=>"10");
$achievements[626]=array("title"=>"With Needle in Hand I", "points"=>"5");
$achievements[627]=array("title"=>"With Needle in Hand II", "points"=>"5");
$achievements[628]=array("title"=>"With Needle in Hand III", "points"=>"10");
$achievements[629]=array("title"=>"With Pestle in Hand I", "points"=>"5");
$achievements[630]=array("title"=>"With Pestle in Hand II", "points"=>"5");
$achievements[631]=array("title"=>"With Pestle in Hand III", "points"=>"10");
$achievements[632]=array("title"=>"With Pan in Hand I", "points"=>"5");
$achievements[633]=array("title"=>"With Pan in Hand II", "points"=>"5");
$achievements[634]=array("title"=>"With Pan in Hand III", "points"=>"10");
$achievements[635]=array("title"=>"With Pick in Hand I", "points"=>"5");
$achievements[636]=array("title"=>"With Pick in Hand II", "points"=>"5");
$achievements[637]=array("title"=>"With Pick in Hand III", "points"=>"10");
$achievements[638]=array("title"=>"With Axe in Hand I", "points"=>"5");
$achievements[639]=array("title"=>"With Axe in Hand II", "points"=>"5");
$achievements[640]=array("title"=>"With Axe in Hand III", "points"=>"10");
$achievements[641]=array("title"=>"With Bait in Hand I", "points"=>"5");
$achievements[642]=array("title"=>"With Bait in Hand II", "points"=>"5");
$achievements[643]=array("title"=>"With Bait in Hand III", "points"=>"10");
$achievements[323]=array("title"=>"All the More Region to Leve I", "points"=>"5");
$achievements[324]=array("title"=>"All the More Region to Leve II", "points"=>"5");
$achievements[325]=array("title"=>"All the More Region to Leve III", "points"=>"5");
$achievements[326]=array("title"=>"All the More Region to Leve IV", "points"=>"5");
$achievements[327]=array("title"=>"All the More Region to Leve V", "points"=>"5");
$achievements[328]=array("title"=>"All the More Region to Leve VI", "points"=>"10");
$achievements[329]=array("title"=>"Region d'Etre", "points"=>"20");
$achievements[330]=array("title"=>"Think Global, Quest Local I", "points"=>"5");
$achievements[331]=array("title"=>"Think Global, Quest Local II", "points"=>"5");
$achievements[332]=array("title"=>"Think Global, Quest Local III", "points"=>"5");
$achievements[333]=array("title"=>"Think Global, Quest Local IV", "points"=>"5");
$achievements[334]=array("title"=>"Think Global, Quest Local V", "points"=>"5");
$achievements[335]=array("title"=>"Think Global, Quest Local VI", "points"=>"10");
$achievements[336]=array("title"=>"Lost in Localization", "points"=>"20");
$achievements[601]=array("title"=>"In the Outfield I", "points"=>"5");
$achievements[602]=array("title"=>"In the Outfield II", "points"=>"5");
$achievements[603]=array("title"=>"In the Outfield III", "points"=>"5");
$achievements[604]=array("title"=>"In the Outfield IV", "points"=>"5");
$achievements[605]=array("title"=>"In the Outfield V", "points"=>"5");
$achievements[606]=array("title"=>"In the Outfield VI", "points"=>"10");
$achievements[607]=array("title"=>"Field of Dreams", "points"=>"20");
$achievements[863]=array("title"=>"You Bet Your Ash I", "points"=>"5");
$achievements[864]=array("title"=>"You Bet Your Ash II", "points"=>"5");
$achievements[865]=array("title"=>"You Bet Your Ash III", "points"=>"10");
$achievements[866]=array("title"=>"A Real Bad Ash", "points"=>"20");
$achievements[867]=array("title"=>"Sylph-conscious I", "points"=>"5");
$achievements[868]=array("title"=>"Sylph-conscious II", "points"=>"5");
$achievements[869]=array("title"=>"Sylph-conscious III", "points"=>"10");
$achievements[870]=array("title"=>"Sylph-assured", "points"=>"20");
$achievements[904]=array("title"=>"Fortune Favors the Kobold I", "points"=>"5");
$achievements[905]=array("title"=>"Fortune Favors the Kobold II", "points"=>"5");
$achievements[906]=array("title"=>"Fortune Favors the Kobold III", "points"=>"10");
$achievements[907]=array("title"=>"Kobold as Brass", "points"=>"20");
$achievements[908]=array("title"=>"Gilling Me Softly I", "points"=>"5");
$achievements[909]=array("title"=>"Gilling Me Softly II", "points"=>"5");
$achievements[910]=array("title"=>"Gilling Me Softly III", "points"=>"10");
$achievements[911]=array("title"=>"Licensed to Gill", "points"=>"20");
$achievements[1022]=array("title"=>"Bird Is the Word I", "points"=>"5");
$achievements[1023]=array("title"=>"Bird Is the Word II", "points"=>"5");
$achievements[1024]=array("title"=>"Bird Is the Word III", "points"=>"10");
$achievements[1025]=array("title"=>"That's Ixal, Folks", "points"=>"20");
$achievements[1026]=array("title"=>"Sore Thumb", "points"=>"20");
$achievements[811]=array("title"=>"Cascadier Reborn", "points"=>"10");
$achievements[812]=array("title"=>"Oh My Gourd", "points"=>"10");
$achievements[874]=array("title"=>"Cold as Ice", "points"=>"10");
$achievements[875]=array("title"=>"Horsing About", "points"=>"10");
$achievements[903]=array("title"=>"Eggstreme Hunting", "points"=>"10");
$achievements[1002]=array("title"=>"All's Faire in Love and War", "points"=>"10");
$achievements[1003]=array("title"=>"A Bloom with a View", "points"=>"10");
$achievements[1027]=array("title"=>"Monster Party", "points"=>"10");
$achievements[647]=array("title"=>"Mapping the Realm: Middle La Noscea", "points"=>"10");
$achievements[648]=array("title"=>"Mapping the Realm: Lower La Noscea", "points"=>"10");
$achievements[649]=array("title"=>"Mapping the Realm: Eastern La Noscea", "points"=>"10");
$achievements[650]=array("title"=>"Mapping the Realm: Western La Noscea", "points"=>"10");
$achievements[651]=array("title"=>"Mapping the Realm: Upper La Noscea", "points"=>"10");
$achievements[677]=array("title"=>"Mapping the Realm: Outer La Noscea", "points"=>"10");
$achievements[663]=array("title"=>"Mapping the Realm: Sastasha", "points"=>"10");
$achievements[664]=array("title"=>"Mapping the Realm: Brayflox's Longstop", "points"=>"10");
$achievements[665]=array("title"=>"Mapping the Realm: Wanderer's Palace", "points"=>"10");
$achievements[873]=array("title"=>"Mapping the Realm: Pharos Sirius", "points"=>"10");
$achievements[896]=array("title"=>"Remapping the Realm: Brayflox's Longstop", "points"=>"10");
$achievements[680]=array("title"=>"Mapping the Realm: The Binding Coil of Bahamut I", "points"=>"10");
$achievements[681]=array("title"=>"Mapping the Realm: The Binding Coil of Bahamut II", "points"=>"10");
$achievements[682]=array("title"=>"Mapping the Realm: The Binding Coil of Bahamut III", "points"=>"10");
$achievements[684]=array("title"=>"Mapping the Realm: The Binding Coil of Bahamut V", "points"=>"10");
$achievements[993]=array("title"=>"Mapping the Realm: Hullbreaker Isle", "points"=>"10");
$achievements[657]=array("title"=>"Mapping the Realm: Central Shroud", "points"=>"10");
$achievements[658]=array("title"=>"Mapping the Realm: East Shroud", "points"=>"10");
$achievements[659]=array("title"=>"Mapping the Realm: South Shroud", "points"=>"10");
$achievements[660]=array("title"=>"Mapping the Realm: North Shroud", "points"=>"10");
$achievements[669]=array("title"=>"Mapping the Realm: Tam-Tara Deepcroft", "points"=>"10");
$achievements[673]=array("title"=>"Mapping the Realm: Thousand Maws of Toto-Rak", "points"=>"10");
$achievements[670]=array("title"=>"Mapping the Realm: Haukke Manor", "points"=>"10");
$achievements[671]=array("title"=>"Mapping the Realm: Amdapor Keep", "points"=>"10");
$achievements[872]=array("title"=>"Remapping the Realm: Haukke Manor", "points"=>"10");
$achievements[897]=array("title"=>"Mapping the Realm: The Lost City of Amdapor", "points"=>"10");
$achievements[890]=array("title"=>"Mapping the Realm: The Second Coil of Bahamut I", "points"=>"10");
$achievements[891]=array("title"=>"Mapping the Realm: The Second Coil of Bahamut II", "points"=>"10");
$achievements[892]=array("title"=>"Mapping the Realm: The Second Coil of Bahamut III", "points"=>"10");
$achievements[991]=array("title"=>"Remapping the Realm: Tam-Tara Deepcroft", "points"=>"10");
$achievements[652]=array("title"=>"Mapping the Realm: Western Thanalan", "points"=>"10");
$achievements[653]=array("title"=>"Mapping the Realm: Central Thanalan", "points"=>"10");
$achievements[654]=array("title"=>"Mapping the Realm: Eastern Thanalan", "points"=>"10");
$achievements[655]=array("title"=>"Mapping the Realm: Southern Thanalan", "points"=>"10");
$achievements[656]=array("title"=>"Mapping the Realm: Northern Thanalan", "points"=>"10");
$achievements[666]=array("title"=>"Mapping the Realm: Copperbell Mines", "points"=>"10");
$achievements[667]=array("title"=>"Mapping the Realm: Halatali", "points"=>"10");
$achievements[668]=array("title"=>"Mapping the Realm: Sunken Temple of Qarn", "points"=>"10");
$achievements[674]=array("title"=>"Mapping the Realm: Cutter's Cry", "points"=>"10");
$achievements[678]=array("title"=>"Mapping the Realm: Castrum Meridianum", "points"=>"10");
$achievements[679]=array("title"=>"Mapping the Realm: Praetorium", "points"=>"10");
$achievements[871]=array("title"=>"Remapping the Realm: Copperbell Mines", "points"=>"10");
$achievements[895]=array("title"=>"Remapping the Realm: Halatali", "points"=>"10");
$achievements[661]=array("title"=>"Mapping the Realm: Coerthas Central Highlands", "points"=>"10");
$achievements[672]=array("title"=>"Mapping the Realm: Stone Vigil", "points"=>"10");
$achievements[675]=array("title"=>"Mapping the Realm: Dzemael Darkhold", "points"=>"10");
$achievements[676]=array("title"=>"Mapping the Realm: Aurum Vale", "points"=>"10");
$achievements[992]=array("title"=>"Remapping the Realm: Stone Vigil", "points"=>"10");
$achievements[662]=array("title"=>"Mapping the Realm: Mor Dhona", "points"=>"10");
$achievements[884]=array("title"=>"Mapping the Realm: Labyrinth of the Ancients", "points"=>"10");
$achievements[996]=array("title"=>"Mapping the Realm: Syrcus Tower", "points"=>"10");
$achievements[589]=array("title"=>"I Make This Look Good", "points"=>"5");
$achievements[590]=array("title"=>"My Little Chocobo", "points"=>"5");
$achievements[591]=array("title"=>"Pimp Your Ride", "points"=>"5");
$achievements[527]=array("title"=>"All Watched Over by a Maelstrom of Loving Grace", "points"=>"5");
$achievements[530]=array("title"=>"A Storm of Seals I", "points"=>"5");
$achievements[531]=array("title"=>"A Storm of Seals II", "points"=>"5");
$achievements[532]=array("title"=>"A Storm of Seals III", "points"=>"10");
$achievements[533]=array("title"=>"The Ruby Anchor", "points"=>"20");
$achievements[542]=array("title"=>"In Good Company: Maelstrom I", "points"=>"5");
$achievements[543]=array("title"=>"In Good Company: Maelstrom II", "points"=>"5");
$achievements[544]=array("title"=>"In Good Company: Maelstrom III", "points"=>"10");
$achievements[545]=array("title"=>"The Turquoise Cannon", "points"=>"20");
$achievements[554]=array("title"=>"Fueling the Storm I", "points"=>"5");
$achievements[555]=array("title"=>"Fueling the Storm II", "points"=>"5");
$achievements[556]=array("title"=>"Fueling the Storm III", "points"=>"10");
$achievements[557]=array("title"=>"The Onyx Oars", "points"=>"20");
$achievements[566]=array("title"=>"To Each According to His Need: Maelstrom I", "points"=>"5");
$achievements[567]=array("title"=>"To Each According to His Need: Maelstrom II", "points"=>"5");
$achievements[568]=array("title"=>"To Each According to His Need: Maelstrom III", "points"=>"10");
$achievements[569]=array("title"=>"The Jade Mast", "points"=>"20");
$achievements[686]=array("title"=>"In the Red I", "points"=>"5");
$achievements[687]=array("title"=>"In the Red II", "points"=>"5");
$achievements[688]=array("title"=>"In the Red III", "points"=>"10");
$achievements[736]=array("title"=>"Bump on a Log: Maelstrom", "points"=>"20");
$achievements[528]=array("title"=>"Snakebitten", "points"=>"5");
$achievements[534]=array("title"=>"A Snake in the Brass I", "points"=>"5");
$achievements[535]=array("title"=>"A Snake in the Brass II", "points"=>"5");
$achievements[536]=array("title"=>"A Snake in the Brass III", "points"=>"10");
$achievements[537]=array("title"=>"The Mahogany Leaf", "points"=>"20");
$achievements[546]=array("title"=>"In Good Company: Twin Adder I", "points"=>"5");
$achievements[547]=array("title"=>"In Good Company: Twin Adder II", "points"=>"5");
$achievements[548]=array("title"=>"In Good Company: Twin Adder III", "points"=>"10");
$achievements[549]=array("title"=>"The Ironwood Leaf", "points"=>"20");
$achievements[558]=array("title"=>"Feeding the Serpent I", "points"=>"5");
$achievements[559]=array("title"=>"Feeding the Serpent II", "points"=>"5");
$achievements[560]=array("title"=>"Feeding the Serpent III", "points"=>"10");
$achievements[561]=array("title"=>"The Sycamore Leaf", "points"=>"20");
$achievements[570]=array("title"=>"To Each According to His Need: Twin Adder I", "points"=>"5");
$achievements[571]=array("title"=>"To Each According to His Need: Twin Adder II", "points"=>"5");
$achievements[572]=array("title"=>"To Each According to His Need: Twin Adder III", "points"=>"10");
$achievements[573]=array("title"=>"The Willow Leaf", "points"=>"20");
$achievements[689]=array("title"=>"In the Yellow I", "points"=>"5");
$achievements[690]=array("title"=>"In the Yellow II", "points"=>"5");
$achievements[691]=array("title"=>"In the Yellow III", "points"=>"10");
$achievements[737]=array("title"=>"Bump on a Log: Order of the Twin Adder", "points"=>"20");
$achievements[529]=array("title"=>"Light My Fire", "points"=>"5");
$achievements[538]=array("title"=>"Burning a Hole in My Pocket I", "points"=>"5");
$achievements[539]=array("title"=>"Burning a Hole in My Pocket II", "points"=>"5");
$achievements[540]=array("title"=>"Burning a Hole in My Pocket III", "points"=>"10");
$achievements[541]=array("title"=>"The Mythril Scales", "points"=>"20");
$achievements[550]=array("title"=>"In Good Company: Immortal Flames I", "points"=>"5");
$achievements[551]=array("title"=>"In Good Company: Immortal Flames II", "points"=>"5");
$achievements[552]=array("title"=>"In Good Company: Immortal Flames III", "points"=>"10");
$achievements[553]=array("title"=>"The Silver Scales", "points"=>"20");
$achievements[562]=array("title"=>"Fanning the Flames I", "points"=>"5");
$achievements[563]=array("title"=>"Fanning the Flames II", "points"=>"5");
$achievements[564]=array("title"=>"Fanning the Flames III", "points"=>"10");
$achievements[565]=array("title"=>"The Brass Scales", "points"=>"20");
$achievements[574]=array("title"=>"To Each According to His Need: Immortal Flames I", "points"=>"5");
$achievements[575]=array("title"=>"To Each According to His Need: Immortal Flames II", "points"=>"5");
$achievements[576]=array("title"=>"To Each According to His Need: Immortal Flames III", "points"=>"10");
$achievements[577]=array("title"=>"The Bronze Scales", "points"=>"20");
$achievements[692]=array("title"=>"In the Black I", "points"=>"5");
$achievements[693]=array("title"=>"In the Black II", "points"=>"5");
$achievements[694]=array("title"=>"In the Black III", "points"=>"10");
$achievements[738]=array("title"=>"Bump on a Log: Immortal Flames", "points"=>"20");
/*
  $achievements[]=array("title"=>"Dreams of Ice","points"=>"");
  $achievements[]=array("title"=>"Uncoiled","points"=>"");
  $achievements[]=array("title"=>"Imagine Dragon","points"=>"");
  $achievements[]=array("title"=>"Go Big or Go Home VIII","points"=>"");
  $achievements[]=array("title"=>"Go Big or Go Home IX","points"=>"");
  $achievements[]=array("title"=>"Go Big or Go Home X","points"=>"");
  $achievements[]=array("title"=>"Leaving a Better Impression I","points"=>"");
  $achievements[]=array("title"=>"Leaving a Better Impression II","points"=>"");
  $achievements[]=array("title"=>"Remapping the Realm: Sunken Temple of Qarn","points"=>"");
  $achievements[]=array("title"=>"Remapping the Realm: Sastasha","points"=>"");
  $achievements[]=array("title"=>"Mapping the Realm: Snowcloak","points"=>"");
  $achievements[]=array("title"=>"Out of a Bind I","points"=>"");
  $achievements[]=array("title"=>"Out of a Bind II","points"=>"");
  $achievements[]=array("title"=>"Out of a Bind III","points"=>"");
  $achievements[]=array("title"=>"Mapping the Realm: The Final Coil of Bahamut I","points"=>"");
  $achievements[]=array("title"=>"Mapping the Realm: The Final Coil of Bahamut II","points"=>"");
  $achievements[]=array("title"=>"Let it Go","points"=>"");
  $achievements[]=array("title"=>"Come on, Rogue I","points"=>"");
  $achievements[]=array("title"=>"Come on, Rogue II","points"=>"");
  $achievements[]=array("title"=>"Come on, Rogue III","points"=>"");
  $achievements[]=array("title"=>"Come on, Rogue IV","points"=>"");
  $achievements[]=array("title"=>"Come on, Rogue V","points"=>"");
  $achievements[]=array("title"=>"Bump on a Log: Rogue","points"=>"");
  $achievements[]=array("title"=>"Against the Ninja","points"=>"");
  $achievements[]=array("title"=>"Yoshimitsu's Island","points"=>""); */

function AchievementsPublic($Array)
{
// dirty indeed
    if (isset($Array[0]))
    {
        if (stripos($Array[0][0], 'do not have permission')!==false)
        {
            return false;
        }
    }

    return true;
}
?>
